statistiques ski/statistiques ski/Controllers/CentreDeSkisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using statistiques_ski.DAL;
using statistiques_ski.Models;

namespace statistiques_ski.Controllers
{
    public class CentreDeSkisController : Controller
    {
        //private Statistiques_SkiContext db = new Statistiques_SkiContext();
		private UnitOfWork unitOfWork = new UnitOfWork();

        // GET: CentreDeSkis
        public ActionResult Index()
        {
			var centreDeSkis = unitOfWork.CentreDeSkiRepository.GetForSkieur(unitOfWork.CurrentUserID);//db.CentreDeSkis.Include(c => c.Region).Include(c => c.Skieur);
            return View(centreDeSkis.ToList());
        }

        // GET: CentreDeSkis/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
			CentreDeSki centreDeSki = unitOfWork.CentreDeSkiRepository.GetByID((int)id);
            if (centreDeSki == null)
            {
                return HttpNotFound();
            }
            return View(centreDeSki);
        }

        // GET: CentreDeSkis/Create
        public ActionResult Create()
        {
			ViewBag.RegionID = new SelectList(unitOfWork.RegionRepository.Get(), "RegionID", "NomRegion");
			ViewBag.SkieurID = new SelectList(unitOfWork.SkieurRepository.Get(), "SkieurID", "Nom");
            return View();
        }

        // POST: CentreDeSkis/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CentreDeSkiID,Nom,Adresse,NbPistes,Altitude,RegionID,SkieurID")] CentreDeSki centreDeSki)
        {
            if (ModelState.IsValid)
            {
				unitOfWork.CentreDeSkiRepository.Insert(centreDeSki);
				unitOfWork.Save();
                return RedirectToAction("Index");
            }

			ViewBag.RegionID = new SelectList(unitOfWork.RegionRepository.Get(), "RegionID", "NomRegion", centreDeSki.RegionID);
			ViewBag.SkieurID = new SelectList(unitOfWork.SkieurRepository.Get(), "SkieurID", "Nom", centreDeSki.Region.SkieurID);
            return View(centreDeSki);
        }

        // GET: CentreDeSkis/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
			CentreDeSki centreDeSki = unitOfWork.CentreDeSkiRepository.GetByID((int)id);
            if (centreDeSki == null)
            {
                return HttpNotFound();
            }
			ViewBag.RegionID = new SelectList(unitOfWork.RegionRepository.Get(), "RegionID", "NomRegion", centreDeSki.RegionID);
			ViewBag.SkieurID = new SelectList(unitOfWork.SkieurRepository.Get(), "SkieurID", "Nom", centreDeSki.Region.SkieurID);
            return View(centreDeSki);
        }

        // POST: CentreDeSkis/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CentreDeSkiID,Nom,Adresse,NbPistes,Altitude,RegionID,SkieurID")] CentreDeSki centreDeSki)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(centreDeSki).State = EntityState.Modified;
				unitOfWork.CentreDeSkiRepository.Update(centreDeSki);
				unitOfWork.Save();
                return RedirectToAction("Index");
            }
			ViewBag.RegionID = new SelectList(unitOfWork.RegionRepository.Get(), "RegionID", "NomRegion", centreDeSki.RegionID);
			ViewBag.SkieurID = new SelectList(unitOfWork.SkieurRepository.Get(), "SkieurID", "Nom", centreDeSki.Region.SkieurID);
            return View(centreDeSki);
        }

        // GET: CentreDeSkis/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
			CentreDeSki centreDeSki = unitOfWork.CentreDeSkiRepository.GetForSkieurByID((int)id, unitOfWork.CurrentUserID);
            if (centreDeSki == null)
            {
                return HttpNotFound();
            }
            return View(centreDeSki);
        }

        // POST: CentreDeSkis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
			CentreDeSki centreDeSki = unitOfWork.CentreDeSkiRepository.GetForSkieurByID((int)id, unitOfWork.CurrentUserID);
			unitOfWork.CentreDeSkiRepository.Delete(centreDeSki);
			unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

statistiques ski/statistiques ski/Controllers/RegionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using statistiques_ski.DAL;
using statistiques_ski.Models;

namespace statistiques_ski.Controllers
{
    public class RegionsController : Controller
    {
        UnitOfWork uow = new UnitOfWork();

        // GET: Regions
        public ActionResult Index(bool? isEmpty)
        {
            var regions = uow.RegionRepository.GetForSkieur(uow.CurrentUserID);
            return View(regions.ToList());
        }

        // GET: Regions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Region region = uow.RegionRepository.GetForSkieurByID((int)id, uow.CurrentUserID);
            if (region == null)
            {
                return HttpNotFound();
            }
            return View(region);
        }

        // GET: Regions/Create
        public ActionResult Create()
        {
            //ViewBag.SkieurID = new SelectList(uow.SkieurRepository.Get(), "SkieurID", "Nom");
            return View();
        }

        // POST: Regions/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RegionID,NomRegion")] Region region)
        {
            if (ModelState.IsValid)
            {
                uow.RegionRepository.Insert(region);
                region.SkieurID = uow.CurrentUserID;
                uow.Save();
                return RedirectToAction("Index");
            }

            ViewBag.SkieurID = new SelectList(uow.SkieurRepository.Get(), "SkieurID", "Nom", uow.CurrentUserID);
            return View(region);
        }

        // GET: Regions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Region region = uow.RegionRepository.GetForSkieurByID((int)id, uow.CurrentUserID);
            if (region == null)
            {
                return HttpNotFound();
            }
            //ViewBag.SkieurID = new SelectList(uow.SkieurRepository.Get(), "SkieurID", "Nom", region.SkieurID);
            return View(region);
        }

        // POST: Regions/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RegionID,NomRegion")] Region region)
        {
            if (ModelState.IsValid)
            {
                uow.RegionRepository.Update(region);
                region.SkieurID = uow.CurrentUserID;
                uow.Save();
                return RedirectToAction("Index");
            }
            ViewBag.SkieurID = new SelectList(uow.SkieurRepository.Get(), "SkieurID", "Nom", uow.CurrentUserID);
            return View(region);
        }

        // GET: Regions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Region region = uow.RegionRepository.GetForSkieurByID((int)id, uow.CurrentUserID);
            if (region == null)
            {
                return HttpNotFound();
            }
            return View(region);
        }

        // POST: Regions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Region region = uow.RegionRepository.GetForSkieurByID((int)id, uow.CurrentUserID);
            uow.RegionRepository.Delete(region);
            uow.Save();
            return RedirectToAction("Index");
        }
    }
}

statistiques ski/statistiques ski/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - Mon application ASP.NET</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
</head>
<body>
	<div class="navbar navbar-fixed-top" id="header">
		<ul class="header-inner" style="display:inline-block!important">
			<li class="logo">
				@Html.ActionLink("Statistiques de ski", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
			</li>
		</ul>
		<ul class="header-inner nav" style="display:inline-block!important">
			<li class="white_text">@Html.ActionLink("Centres de Ski", "Index", "CentreDeSkis")</li>
			<li class="white_text">@Html.ActionLink("Régions", "Index", "Regions")</li>
			<li class="white_text">@Html.ActionLink("Saisons", "Index", "Saisons")</li>
			<li class="white_text">@Html.ActionLink("Sorties", "Index", "Sorties")</li>
			<li class="white_text">@Html.ActionLink("Statistiques", "Index", "Statistiques")</li>
			<li class="white_text">@Html.ActionLink("À propos de", "About", "Home")</li>
			<li class="white_text">@Html.ActionLink("Contact", "Contact", "Home")</li>
		</ul>

		<!--<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			@Html.ActionLink("Nom de l'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
		</div>

		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li>@Html.ActionLink("Centres de Ski", "Index", "CentreDeSkis")</li>
				<li>@Html.ActionLink("Régions", "Index", "Regions")</li>
				<li>@Html.ActionLink("Saisons", "Index", "Saisons")</li>
				<li>@Html.ActionLink("Sorties", "Index", "Sorties")</li>
				<li>@Html.ActionLink("Statistiques", "Index", "Statistiques")</li>
				<li>@Html.ActionLink("À propos de", "About", "Home")</li>
				<li>@Html.ActionLink("Contact", "Contact", "Home")</li>
			</ul>
		</div>
		-->
	</div>
	</div>
	<div class="container body-content">
		@RenderBody()
	</div>
	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)
</body>
</html>